### PR TITLE
Update Skills all functionalities

### PR DESCRIPTION
**Pull request by tzuminglu**
The Gif can help you out to operate this section. Not doing all the error handling yet. Will do it later on.

Step 1: https://www.kapwing.com/videos/6445478a633aa30017074e36
Step 2: https://www.kapwing.com/videos/64454884ad7e7800b9e11353

### CODE REVIEW

**Review by JosephMarks — APPROVED** [review]
Looks great @tzuminglu - nice work on skills functionalities! Approved 🥇

**Comment by tzuminglu** [comment]
Hi Guys,

Hope you are all doing well! I just finish network and skill secions' functionalities and authentication. You can register an account and login to play around all the functionalities.

The session part I have already put the userId that you can use req.session.user.userId to reach out the user ID, the user ID has been convert to string and won't have to convert it again.
Studio_Project (3)

Below link is the GIF would help you out.
Studio_Project (3)

**Review by pradyumn25 — COMMENTED** [review]
lgtm !

**Comment by pradyumn25** [comment]
I have also update Bcrypt to BcryptJS as it was having conflict, prof. also mentioned about this in his lecture to use Bcrypt js

**Review by pradyumn25 — APPROVED** [review]

**Pull request merged**
