### PR TITLE
Finish networks route and must of the functionalities. Remaining like and search functionalities need to be done.

### PR DESCRIPTION
**Pull request by tzuminglu**

### CODE REVIEW

**Comment by tzuminglu** [comment]
Hi guys,

This is the video recording can help you out to play around the network part. Please fnd it out and help me to check the unfound bugs >< 

Thank you.

https://youtu.be/bOUMnBDpOTo

**Review by JosephMarks — APPROVED** [review]

**Comment by pradyumn25** [comment]
Looks good to me, everything thing is working fine for me !
 Just include a HTML page to showcase the error message ! rather than sending the JSON.

**Review by pradyumn25 — APPROVED** [review]

**Comment by tzuminglu** [comment]
OK! Will update these parts in the next time.

**Review by JosephMarks — COMMENTED** [review]
Looks good - nice work @tzuminglu !

**Pull request merged**
